# Generated by Django 6.0.5 on 2026-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backendtools',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
