# Generated by Django 6.0.5 on 2026-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_backendtools_project_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='language',
            new_name='css',
        ),
        migrations.AddField(
            model_name='project',
            name='database',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='html',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='js',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
