# Generated by Django 6.0.5 on 2026-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_language_project_css_project_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('pdf', models.FileField(upload_to='notes/')),
            ],
        ),
    ]
