# Generated by Django 6.0.5 on 2026-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_webnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnote',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
