# Generated by Django 6.0.5 on 2026-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='cv/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
