# Generated by Django 6.0.5 on 2026-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backendtools',
            field=models.CharField(max_length=20),
        ),
    ]
